In [2]:
import pandas as pd
df=pd.read_csv("../data/pm25_raw.csv")
df.head()

           datetime_utc  pm25
0  2025-05-01T00:00:00Z  64.0
1  2025-05-01T00:30:00Z  64.0
2  2025-05-01T00:45:00Z  64.0
3  2025-05-01T01:15:00Z  88.0
4  2025-05-01T01:30:00Z  88.0

In [5]:
datetime_utc.dtype

NameError: name 'datetime_utc' is not defined

In [7]:
df['datetime_utc'].dtypes

In [8]:
df['pm25'].isnull().sum()

np.int64(0)

In [14]:
df.duplicated(keep='first').sum()

np.int64(6)

In [15]:
df[df.duplicated(keep=False)]

              datetime_utc  pm25
999   2025-05-18T15:45:00Z  29.0
1000  2025-05-18T15:45:00Z  29.0
1999  2025-06-02T05:45:00Z  27.0
2000  2025-06-02T05:45:00Z  27.0
2999  2025-06-15T05:45:00Z  28.0
3000  2025-06-15T05:45:00Z  28.0
3999  2025-07-01T00:00:00Z  29.0
4000  2025-07-01T00:00:00Z  29.0
4999  2025-07-12T20:00:00Z  28.0
5000  2025-07-12T20:00:00Z  28.0
5999  2025-07-24T03:30:00Z  24.0
6000  2025-07-24T03:30:00Z  24.0

In [16]:
df['datetime_utc'] = pd.to_datetime(df['datetime_utc'])

In [17]:
df.dtypes

datetime_utc    datetime64[us, UTC]
pm25                        float64
dtype: object

In [5]:
df=pd.read_csv("../data/pm25_raw.csv")

In [6]:
df.duplicated(keep=False).sum()

np.int64(12)

In [1]:
import requests, os
from dotenv import load_dotenv
load_dotenv()

headers = {"X-API-KEY": os.getenv("OPENAQ_API_KEY")}
params = {
    "datetime_from": "2025-05-18T15:45:01Z",
    "datetime_to": "2025-05-18T16:15:00Z",
    "limit": 5
}
r = requests.get("https://api.openaq.org/v3/sensors/12234921/measurements", headers=headers, params=params)
r.json()["results"]

[{'value': 29.0,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': 'raw',
   'interval': '00:15:00',
   'datetimeFrom': {'utc': '2025-05-18T15:45:00Z',
    'local': '2025-05-18T21:15:00+05:30'},
   'datetimeTo': {'utc': '2025-05-18T16:00:00Z',
    'local': '2025-05-18T21:30:00+05:30'}},
  'coordinates': None,
  'summary': None,
  'coverage': {'expectedCount': 1,
   'expectedInterval': '00:15:00',
   'observedCount': 1,
   'observedInterval': '00:15:00',
   'percentComplete': 100.0,
   'percentCoverage': 100.0,
   'datetimeFrom': {'utc': '2025-05-18T15:45:00Z',
    'local': '2025-05-18T21:15:00+05:30'},
   'datetimeTo': {'utc': '2025-05-18T16:00:00Z',
    'local': '2025-05-18T21:30:00+05:30'}}},
 {'value': 33.0,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': 'raw',
   'interval': '00:15:00',
   'datetimeFrom': {'utc': '2025-05-18T16:00:00Z',
    'local': '2025-05-18T21:30:00+05:30'},
   'datetimeTo': {'utc': '2025-05-18T16:15:00Z',
    'local': '2025-05-18T21:45:00+05:30'}},
  'coordinates': None,
  'summary': None,
  'coverage': {'expectedCount': 1,
   'expectedInterval': '00:15:00',
   'observedCount': 1,
   'observedInterval': '00:15:00',
   'percentComplete': 100.0,
   'percentCoverage': 100.0,
   'datetimeFrom': {'utc': '2025-05-18T16:00:00Z',
    'local': '2025-05-18T21:30:00+05:30'},
   'datetimeTo': {'utc': '2025-05-18T16:15:00Z',
    'local': '2025-05-18T21:45:00+05:30'}}}]