In [2]:
import pandas as pd
df=pd.read_csv("../data/pm25_raw.csv")
df.head()

           datetime_utc  pm25
0  2025-05-01T00:00:00Z  64.0
1  2025-05-01T00:30:00Z  64.0
2  2025-05-01T00:45:00Z  64.0
3  2025-05-01T01:15:00Z  88.0
4  2025-05-01T01:30:00Z  88.0

In [3]:
datetime_utc.dtype

NameError: name 'datetime_utc' is not defined

In [5]:
df['datetime_utc'].dtypes

In [6]:
df['pm25'].isnull().sum()

np.int64(0)

In [7]:
df.duplicated(keep='first').sum()

np.int64(0)

In [8]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [datetime_utc, pm25]
Index: []

In [16]:
df['datetime_utc'] = pd.to_datetime(df['datetime_utc'])

In [17]:
df.dtypes

datetime_utc    datetime64[us, UTC]
pm25                        float64
dtype: object

In [9]:
df=pd.read_csv("../data/pm25_raw.csv")

In [10]:
df.duplicated(keep=False).sum()

np.int64(0)

In [1]:
import requests, os
from dotenv import load_dotenv
load_dotenv()

headers = {"X-API-KEY": os.getenv("OPENAQ_API_KEY")}
params = {
    "datetime_from": "2025-05-18T15:45:01Z",
    "datetime_to": "2025-05-18T16:15:00Z",
    "limit": 5
}
r = requests.get("https://api.openaq.org/v3/sensors/12234921/measurements", headers=headers, params=params)
r.json()["results"]

[{'value': 29.0,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': 'raw',
   'interval': '00:15:00',
   'datetimeFrom': {'utc': '2025-05-18T15:45:00Z',
    'local': '2025-05-18T21:15:00+05:30'},
   'datetimeTo': {'utc': '2025-05-18T16:00:00Z',
    'local': '2025-05-18T21:30:00+05:30'}},
  'coordinates': None,
  'summary': None,
  'coverage': {'expectedCount': 1,
   'expectedInterval': '00:15:00',
   'observedCount': 1,
   'observedInterval': '00:15:00',
   'percentComplete': 100.0,
   'percentCoverage': 100.0,
   'datetimeFrom': {'utc': '2025-05-18T15:45:00Z',
    'local': '2025-05-18T21:15:00+05:30'},
   'datetimeTo': {'utc': '2025-05-18T16:00:00Z',
    'local': '2025-05-18T21:30:00+05:30'}}},
 {'value': 33.0,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': 'raw',
   'interval': '00:15:00',
   'datetimeFrom': {'utc': '2025-05-18T16:00:00Z',
    'local': '2025-05-18T21:30:00+05:30'},
   'datetimeTo': {'utc': '2025-05-18T16:15:00Z',
    'local': '2025-05-18T21:45:00+05:30'}},
  'coordinates': None,
  'summary': None,
  'coverage': {'expectedCount': 1,
   'expectedInterval': '00:15:00',
   'observedCount': 1,
   'observedInterval': '00:15:00',
   'percentComplete': 100.0,
   'percentCoverage': 100.0,
   'datetimeFrom': {'utc': '2025-05-18T16:00:00Z',
    'local': '2025-05-18T21:30:00+05:30'},
   'datetimeTo': {'utc': '2025-05-18T16:15:00Z',
    'local': '2025-05-18T21:45:00+05:30'}}}]

In [11]:
df.sort_values('datetime_utc')

              datetime_utc  pm25
0     2025-05-01T00:00:00Z  64.0
1     2025-05-01T00:30:00Z  64.0
2     2025-05-01T00:45:00Z  64.0
3     2025-05-01T01:15:00Z  88.0
4     2025-05-01T01:30:00Z  88.0
...                    ...   ...
6696  2025-07-31T22:45:00Z  34.0
6697  2025-07-31T23:00:00Z  28.0
6698  2025-07-31T23:15:00Z  28.0
6699  2025-07-31T23:30:00Z  28.0
6700  2025-07-31T23:45:00Z  28.0

[6701 rows x 2 columns]

In [12]:
df=df.sort_values('datetime_utc').reset_index(drop=True)

In [13]:
df.head()
df.tail()

              datetime_utc  pm25
6696  2025-07-31T22:45:00Z  34.0
6697  2025-07-31T23:00:00Z  28.0
6698  2025-07-31T23:15:00Z  28.0
6699  2025-07-31T23:30:00Z  28.0
6700  2025-07-31T23:45:00Z  28.0

In [14]:
df.head()

           datetime_utc  pm25
0  2025-05-01T00:00:00Z  64.0
1  2025-05-01T00:30:00Z  64.0
2  2025-05-01T00:45:00Z  64.0
3  2025-05-01T01:15:00Z  88.0
4  2025-05-01T01:30:00Z  88.0

In [15]:
df.diff('datetime_utc')

ValueError: periods must be an integer

In [16]:
df['datetime_utc'].diff()

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [17]:
df['datetime_utc'] = pd.to_datetime(df['datetime_utc'])

In [18]:
df['datetime_utc'].dtypes

datetime64[us, UTC]

In [20]:
df['gap']=df['datetime_utc'].diff()

In [21]:
df[df['gap']>pd.Timedelta(minutes=15)]

                  datetime_utc  pm25             gap
1    2025-05-01 00:30:00+00:00  64.0 0 days 00:30:00
3    2025-05-01 01:15:00+00:00  88.0 0 days 00:30:00
9    2025-05-01 04:15:00+00:00  85.0 0 days 01:45:00
10   2025-05-01 06:30:00+00:00  34.0 0 days 02:15:00
13   2025-05-01 09:15:00+00:00  35.0 0 days 02:15:00
...                        ...   ...             ...
6568 2025-07-30 11:30:00+00:00  43.0 0 days 00:30:00
6595 2025-07-30 19:00:00+00:00  30.0 0 days 01:00:00
6652 2025-07-31 09:30:00+00:00  38.0 0 days 00:30:00
6671 2025-07-31 15:00:00+00:00  47.0 0 days 01:00:00
6681 2025-07-31 19:00:00+00:00  41.0 0 days 01:45:00

[396 rows x 3 columns]

In [22]:
df['gap'].max()

Timedelta('1 days 19:00:00')

In [23]:
df=df.set_index('datetime_utc')

In [24]:
df.head()

                           pm25             gap
datetime_utc
2025-05-01 00:00:00+00:00  64.0             NaT
2025-05-01 00:30:00+00:00  64.0 0 days 00:30:00
2025-05-01 00:45:00+00:00  64.0 0 days 00:15:00
2025-05-01 01:15:00+00:00  88.0 0 days 00:30:00
2025-05-01 01:30:00+00:00  88.0 0 days 00:15:00

In [25]:
df_hourly=df['pm25'].resample('h').mean()

In [26]:
df_hourly.head()

datetime_utc
2025-05-01 00:00:00+00:00    64.0
2025-05-01 01:00:00+00:00    88.0
2025-05-01 02:00:00+00:00    85.0
2025-05-01 03:00:00+00:00     NaN
2025-05-01 04:00:00+00:00    85.0
Freq: h, Name: pm25, dtype: float64

In [27]:
df_hourly.isnull().sum()

np.int64(370)

In [28]:
len(df_hourly)

2208

In [29]:
df_hourly=df_hourly.interpolate(limit=2)

In [30]:
df_hourly.isnull().sum()

np.int64(181)

In [31]:
df_hourly[df_hourly.isnull()]

datetime_utc
2025-05-03 08:00:00+00:00   NaN
2025-05-03 09:00:00+00:00   NaN
2025-05-03 10:00:00+00:00   NaN
2025-05-03 11:00:00+00:00   NaN
2025-05-03 12:00:00+00:00   NaN
                             ..
2025-06-30 02:00:00+00:00   NaN
2025-06-30 03:00:00+00:00   NaN
2025-07-04 17:00:00+00:00   NaN
2025-07-04 18:00:00+00:00   NaN
2025-07-04 19:00:00+00:00   NaN
Name: pm25, Length: 181, dtype: float64